#!/bin/bash
#
# Sleepwatcher
# http://superuser.com/questions/635308/how-to-have-an-application-closed-on-lid-close-in-os-x
#

# open ~/Library/Mobile\ Documents/com\~apple\~Automator/Documents/ConnectToNetworkDrive.app
