#/Applications/Racket v6.9/bin
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

#
# Custom
#
if [[ "$OSTYPE" == darwin* ]]; then
  export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
fi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Python pip --user installation path
# http://stackoverflow.com/questions/7143077/how-can-i-install-packages-in-my-home-folder-with-pip
# https://pipenv.readthedocs.io/en/latest/install/#pragmatic-installation-of-pipenv
export PATH="$(python3 -m site --user-base)/bin:$PATH"

# GOPATH
export GOPATH=$HOME/gocode
export PATH=$PATH:$GOPATH/bin

# Racket Path
export PATH=$PATH:"/Applications/Racket v7.6/bin"

# Python encodng issue
# https://stackoverflow.com/a/4027726/524588
export PYTHONIOENCODING="utf_8"

# GNU utils as default
# https://apple.stackexchange.com/a/69332/8271
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# Anaconda3
# https://stackoverflow.com/questions/18675907/how-to-run-conda
export PATH="$HOME/anaconda3/bin:$PATH"
export PATH="$HOME/opt/anaconda3/bin:$PATH"

# Brew Ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
# For compilers to find ruby you may need to set:
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"

# Load pyenv automatically by appending
# the following to ~/.zshrc:

# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"

# Created by `userpath` on 2020-04-15 13:51:38
export PATH="$PATH:/Users/slee/.local/bin"
