#
# Set mvn colors. From https://gist.github.com/1027800
#

# Formatting constants
export BOLD=`tput bold`
export UNDERLINE_ON=`tput smul`
export UNDERLINE_OFF=`tput rmul`
export TEXT_BLACK=`tput setaf 0`
export TEXT_RED=`tput setaf 1`
export TEXT_GREEN=`tput setaf 2`
export TEXT_YELLOW=`tput setaf 3`
export TEXT_BLUE=`tput setaf 4`
export TEXT_MAGENTA=`tput setaf 5`
export TEXT_CYAN=`tput setaf 6`
export TEXT_WHITE=`tput setaf 7`
export BACKGROUND_BLACK=`tput setab 0`
export BACKGROUND_RED=`tput setab 1`
export BACKGROUND_GREEN=`tput setab 2`
export BACKGROUND_YELLOW=`tput setab 3`
export BACKGROUND_BLUE=`tput setab 4`
export BACKGROUND_MAGENTA=`tput setab 5`
export BACKGROUND_CYAN=`tput setab 6`
export BACKGROUND_WHITE=`tput setab 7`
export RESET_FORMATTING=`tput sgr0`

# Wrapper function for Maven's mvn command.
mvn-color()
{
  # Filter mvn output using sed
  mvn $@ | sed -e "s/\(INFO\ :.*\)/${TEXT_BLUE}${BOLD}\1/g" \
							 -e "s/\(WARNING\ :.*\)/${TEXT_BLUE}${BOLD}\1/g" \
							 -e "s/\(ERROR\ :.*\)/${TEXT_BLUE}${BOLD}\1/g" \
							 -e "s/\(\[INFO\]\ \-.*\)/${TEXT_BLUE}${BOLD}\1/g" \
               -e "s/\(\[INFO\]\ \[.*\)/${RESET_FORMATTING}${BOLD}\1${RESET_FORMATTING}/g" \
               -e "s/\(\[INFO\]\ BUILD SUCCESSFUL\)/${BOLD}${TEXT_GREEN}\1${RESET_FORMATTING}/g" \
               -e "s/\(\[WARNING\].*\)/${BOLD}${TEXT_YELLOW}\1${RESET_FORMATTING}/g" \
               -e "s/\(\[ERROR\].*\)/${BOLD}${TEXT_RED}\1${RESET_FORMATTING}/g" \
               -e "s/Tests run: \([^,]*\), Failures: \([^,]*\), Errors: \([^,]*\), Skipped: \([^,]*\)/${BOLD}${TEXT_GREEN}Tests run: \1${RESET_FORMATTING}, Failures: ${BOLD}${TEXT_RED}\2${RESET_FORMATTING}, Errors: ${BOLD}${TEXT_RED}\3${RESET_FORMATTING}, Skipped: ${BOLD}${TEXT_YELLOW}\4${RESET_FORMATTING}/g"

  # Make sure formatting is reset
  echo -ne ${RESET_FORMATTING}
}

# Override the mvn command with the colorized one.
alias mvn="mvn-color -Duser.timezone=UTC"

#
# shortcuts. Idea from http://trumaze.blogspot.kr/2011/03/maven-aliases-for-bash.html
#

mvn-run()
{
	echo mvn $@
	eval mvn $@
	echo mvn $@
}

alias mt="mvn-run test"
alias mc="mvn-run clean"
alias mp="mvn-run package"
alias mcp="mc && mp"
alias mps="mvn-run package -Dmaven.test.skip=true"
alias mcps="mc && mp -Dmaven.test.skip=true"
alias ms="mvn-run site"
alias mcv="mvn-run clean verify"
alias mcvs="mvn-run clean verify -Dmaven.test.skip=true"

# Run spring boot server with a debugging option generated by IntelliJ
mboot () {
  mvn spring-boot:run \
    -Drun.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005" && \
    osascript -e 'display notification "Tomcat ended"'
}
